[target.'cfg(all())']
rustflags = [
    "-Wclippy::all",
    "-Wclippy::pedantic",
    "-Wclippy::nursery",
    "-Wclippy::cargo",
    "-Funsafe_code",
    "-Wmissing_docs",
    "-Wmissing_debug_implementations",
    "-Wmissing_copy_implementations",
    "-Wrust_2018_idioms",
    "-Wunreachable_pub",
    "-Wclippy::unwrap_used",
    "-Wclippy::expect_used",
    "-Wclippy::doc_markdown",
    "-Wclippy::redundant_closure",
    "-Wclippy::missing_errors_doc",
    "-Wclippy::explicit_iter_loop",
    "-Wclippy::implicit_clone",
    "-Wclippy::float_arithmetic",
    "-Wclippy::integer_arithmetic",
    "-Wclippy::modulo_arithmetic",
    "-Wclippy::arithmetic_side_effects",
    "-Wclippy::cast_possible_truncation",
    "-Wclippy::cast_sign_loss",
    "-Wclippy::cast_precision_loss",
    "-Wclippy::cast_possible_wrap",
    "-Wclippy::default_trait_access",
    "-Wclippy::used_underscore_binding",
    "-Wclippy::ptr_as_ptr",
    "-Wclippy::ref_option_ref",
] 

[build]
rustflags = ["-C", "target-cpu=native"]  # Optimize for current CPU
rustdocflags = ["-D", "warnings"]  