name: Sync labels from catalyst-ci/feature/add-labels

on:
  workflow_dispatch:
  repository_dispatch:
    types: [catalyst-labels-updated]
  workflow_call:
    inputs:
      delete-other-labels:
        description: "Prune labels not in the spec?"
        type: boolean
        default: false

permissions:
  issues: write

jobs:
  sync:
    uses: input-output-hk/catalyst-ci/.github/workflows/sync-labels.yml@feature/add-labels
